#!/bin/sh

set -eu

case "$*" in
  *"exec -T redis redis-cli --raw EXISTS fulfilled-orders:v1"*)
    printf '%s\n' '1'
    ;;
  *"--set=correlation_id="*)
    identity_query="$(cat)"
    if [ "${FAKE_PHASE3_EXISTING_IDENTITIES:-false}" = true ] \
      && ! printf '%s' "$identity_query" \
        | grep -Fq 'WHERE "CorrelationId" = :correlation_id'; then
      printf '%s\n' \
        '27000000-0000-0000-0000-000000000000|t|t|2' \
        '27111111-1111-1111-1111-111111111111|t|t|2'
    else
      printf '%s\n' '27111111-1111-1111-1111-111111111111|t|t|2'
    fi
    ;;
  *"exec -T postgres psql"*)
    if [ -f "${FAKE_PHASE3_STATE:?}.effects" ]; then
      if [ "${FAKE_PHASE3_EXISTING_EFFECTS:-false}" = true ]; then
        printf '%s\n' '4|4|4|4|8|0|0'
      else
        printf '%s\n' '1|1|1|1|2|0|0'
      fi
    else
      : > "${FAKE_PHASE3_STATE:?}.effects"
      if [ "${FAKE_PHASE3_EXISTING_EFFECTS:-false}" = true ]; then
        printf '%s\n' '3|3|3|3|6|0|0'
      else
        printf '%s\n' '0|0|0|0|0|0|0'
      fi
    fi
    ;;
  *"kafka-console-producer.sh"*)
    while IFS= read -r line; do :; done
    : > "${FAKE_PHASE3_STATE:?}.dlt"
    ;;
  *"kafka-get-offsets.sh"*)
    if [ "${FAKE_PHASE3_NO_DLT:-false}" = true ]; then
      printf '%s\n' 'coffeeshop.orders.v1.dlt:0:0'
    elif [ -f "${FAKE_PHASE3_STATE:?}.dlt" ]; then
      printf '%s\n' 'coffeeshop.orders.v1.dlt:0:2'
    else
      printf '%s\n' 'coffeeshop.orders.v1.dlt:0:0'
    fi
    ;;
  *)
    ;;
esac
