<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CoffeeShop.IntegrationContracts\CoffeeShop.IntegrationContracts.csproj" />
    <ProjectReference Include="..\..\src\CoffeeShop.Messaging.Abstractions\CoffeeShop.Messaging.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\CoffeeShop.Messaging.Dapr\CoffeeShop.Messaging.Dapr.csproj" />
    <ProjectReference Include="..\..\src\CoffeeShop.Messaging.Kafka\CoffeeShop.Messaging.Kafka.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Fixtures\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
