// <auto-generated />
using System;
using CoffeeShop.Modules.Barista.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeShop.Modules.Barista.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BaristaDbContext))]
    partial class BaristaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("barista")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShop.Modules.Barista.Domain.BaristaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("LineItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("TimeIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TimeUp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("items", "barista");
                });

            modelBuilder.Entity("CoffeeShop.Modules.Barista.Infrastructure.Inbox.BaristaInboxMessage", b =>
                {
                    b.Property<string>("HandlerName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Result")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("HandlerName", "MessageId");

                    b.HasIndex("ReceivedAtUtc");

                    b.ToTable("inbox_messages", "barista");
                });

            modelBuilder.Entity("CoffeeShop.Modules.Barista.Infrastructure.Outbox.BaristaOutboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("MessageId");

                    b.HasIndex("LeaseExpiresAtUtc");

                    b.HasIndex("PublishedAtUtc", "NextAttemptAtUtc");

                    b.ToTable("outbox_messages", "barista");
                });
#pragma warning restore 612, 618
        }
    }
}
